# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  workflow_dispatch:
    

jobs:
  hcf_lcm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: generate answers
      run: python calc_hcf_lcm.py > data/answers.txt
    - name: upload answers
      uses: actions/upload-artifact@v2.3.1
      with:
        name: hcf_lcm_answers
        path: data/answers.txt
      
